Draft work
natisun77/group pull request #12
Opened 2019-04-12 20:54 UTC by natisun77

2019-04-14 08:18 UTC, Siril-O requested changes

2019-04-14 08:18 UTC, Siril-O commented on src/homework/homeworks/Animal.java
> +public class Animal implements Serializable {
This is not 9 HW

2019-04-14 08:18 UTC, Siril-O commented on src/homework/homeworks/buildingclasses/MailService.java
> +        mailBox = new HashMap<String, List<T>>() {
better not override hashmap, add this logic where it is used

2019-04-14 08:18 UTC, Siril-O commented on src/homework/homeworks/buildingclasses/MailService.java
> +                    return Collections.emptyList();
do you know that Collections.emptyList() is immutable you can not add to it ?

2019-04-14 08:18 UTC, Siril-O commented on src/homework/homeworks/buildingclasses/entity/Message.java
> +    private String from;
can be final

2019-04-14 08:18 UTC, Siril-O commented on src/homework/homeworks/buildingclasses/Application.java
> +        String randomFrom = "Varya"; // Некоторая случайная строка. Можете выбрать ее самостоятельно.
remove comments split to separate methods

2019-04-14 08:18 UTC, Siril-O commented on src/homework/homeworks/buildingclasses/entity/Salary.java
> +
Where is task 3?

2019-04-14 10:02 UTC, natisun77 commented on src/homework/homeworks/Animal.java
> +public class Animal implements Serializable {
my 6th homework was not approved by that time, so those commits are here

2019-04-14 10:04 UTC, natisun77 commented on src/homework/homeworks/buildingclasses/Application.java
> +        String randomFrom = "Varya"; // Некоторая случайная строка. Можете выбрать ее самостоятельно.
I removed the comments, but the rest are the part of the task

2019-04-14 10:07 UTC, natisun77 commented on src/homework/homeworks/buildingclasses/entity/Salary.java
> +
the third task is not obligatory, it is with *

2019-04-14 10:11 UTC, natisun77 commented on src/homework/homeworks/buildingclasses/MailService.java
> +        mailBox = new HashMap<String, List<T>>() {
what do you mean? I use it in main, but I can not change it, because main is our task here.

2019-04-15 09:01 UTC, Siril-O commented on src/homework/homeworks/Animal.java
> +public class Animal implements Serializable {
each pull request is separate set of functionality

2019-04-15 09:02 UTC, Siril-O commented on src/homework/homeworks/buildingclasses/MailService.java
> +        mailBox = new HashMap<String, List<T>>() {
i mean do not override hash map, do it another way

2019-04-15 09:03 UTC, Siril-O commented on src/homework/homeworks/buildingclasses/entity/Salary.java
> +
So you are not able to solve this task? How you plan to work in real projects?

2019-04-15 09:04 UTC, Siril-O commented on src/homework/homeworks/buildingclasses/entity/Salary.java
> +
I will approve this, fix issues if you want

2019-04-15 09:13 UTC, merged